apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: limemanas/backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_PORT
        - name: ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ELASTICSEARCH_HOST
        - name: ES_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ES_URL
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BASE_URL
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_KEY
